apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: webfixture-controller1
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: webfixture1
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: webfixture1
    spec:
      containers:
        - name: webfixture
          image: hawkularqe/web-fixture:latest
          resources:
            limits:
              cpu: 1
          ports:
            - containerPort: 8080
